[package]
name = "telraam-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["cargo", "derive", "env"] }
geojson = "0.24.1"
humantime-serde = "1.1.1"
reqwest = { version = "0.11", features = [
    "blocking",
    "json",
    "brotli",
    "deflate",
    "gzip",
    "native-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3"
thiserror = "1.0.50"
